export const actionTypes = {
  LOAD_USERS: 'LOAD_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_USER: 'ADD_USER',
  APPLY_SORTING: 'APPLY_SORTING',
  APPLY_FILTER: 'APPLY_FILTER',
  CLEAR_FILTER: 'CLEAR_FILTER',
  NAVIGATE_TO_PAGE: 'NAVIGATE_TO_PAGE'
};